"""empty message

Revision ID: cbe9abd27909
Revises: 97c486fcf47f
Create Date: 2019-11-25 03:28:34.828481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe9abd27909'
down_revision = '97c486fcf47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('qr_code', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'number')
    op.drop_column('order_items', 'qr_code')
    # ### end Alembic commands ###
